apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: germa-keyvault
  namespace: germa
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: "3d4ba9fd-81a8-488b-a620-608fc7c2e0e6"   # Application ID in azurekeyvaultsecretsprovider-gs-datalake-aks
    keyvaultName: "gs-datalake-kv"
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    tenantId: "9131d52f-9d06-41a1-84ba-d4b8a6fcac08"
    objects:  |
      array:
        - |
          objectName: GERMA-DB-CONNECTION-STRING-STAGE
          objectType: secret
          objectVersion: ""
        - |
          objectName: GERMA-DB-CONNECTION-STRING
          objectType: secret
          objectVersion: ""
        - |
          objectName: GERMA-DB-USER
          objectType: secret
          objectVersion: ""
        - |
          objectName: GERMA-DB-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: GF-PROD-DB-HOST
          objectType: secret
          objectVersion: ""
  secretObjects:
    - secretName: germa-secrets
      type: Opaque
      data:
        - key: GERMA-DB-CONNECTION-STRING-STAGE
          objectName: GERMA-DB-CONNECTION-STRING-STAGE
        - key: GERMA-DB-CONNECTION-STRING
          objectName: GERMA-DB-CONNECTION-STRING
        - key: GERMA-DB-USER
          objectName: GERMA-DB-USER
        - key: GERMA-DB-PASSWORD
          objectName: GERMA-DB-PASSWORD
        - key: GF-PROD-DB-HOST
          objectName: GF-PROD-DB-HOST
