FROM mcr.microsoft.com/dotnet/sdk:8.0
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/TimKroeger13/GERMA.git
RUN cd /GERMA/ && git checkout main
RUN chmod -R 755 /GERMA/
RUN /GERMA/Confluence/Install/setup.sh
ENTRYPOINT [ "/bin/bash", "/GERMA/Confluence/Install/run.sh" ]