FROM mcr.microsoft.com/dotnet/sdk:8.0
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/TimKroeger13/GERMA.git /app
RUN cd /app/ && git checkout main
RUN chmod -R 755 /app/
RUN /app/Confluence/Install/setup.sh
ENTRYPOINT [ "/bin/bash", "/app/Confluence/Install/run.sh" ]